_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  MASK_ON: False
  PIXEL_STD: [57.375, 57.120, 58.395]
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 11
SOLVER:
  STEPS: (84000, 94500)
  MAX_ITER: 10000
  IMS_PER_BATCH: 8
  BASE_LR: 0.06
DATASETS:
  TRAIN: ("train",)
  TEST: ("val",)
DATALOADER:
  NUM_WORKERS: 8
OUTPUT_DIR: "/home/lpisaneschi/master_thesis/X101/finetuned_model"