
LATEX_FORMULA = [
    r"(n + 1)a^n u(n) \Leftrightarrow \frac{1}{{(1 - ae^{ - j\omega } )^2 }},\left| a \right| < 1",
    r"\frac{{a\sqrt b }}{{c\sqrt d }} = \frac{a}{c}\sqrt {\frac{b}{d}}",
    r"e^{ + j\omega _o n} x(n) \Leftrightarrow X(e^{j(\omega  - \omega _o )} )",
    r"\frac{{\left( {x - x_0 } \right)^2 }}{{a^2 }} - \frac{{\left( {y - y_0 } \right)^2 }}{{b^2 }} - \frac{{\left( {z - z_0 } \right)^2 }}{{c^2 }} = 1",
    r"\frac{{\Delta E}}{E} =  - \frac{b}{m}T",
    r"\sec \theta  = \frac{{{\rm{Hypotenuse}}}}{{{\rm{Adjacent Side}}}}",
    r"n^3 a^n u(n) \Leftrightarrow \frac{{az(z^2  + 4az + a^2 )}}{{\left( {z - a} \right)^4 }},\left| z \right| > \left| a \right|",
    r"pH =  - \log \left[ {H^ +  } \right]",
    r"R = \frac{{2GM}}{{c^2 }}",
    r"C_p  = \frac{{\Delta H}}{{\Delta T}}",
    r"V = lhw",
    r"\sigma ^2 _b  = npq",
    r"Ku(t) \Leftrightarrow \frac{K}{s}",
    r"y(x,t) = A\sin \left[ {k(x - \upsilon t)} \right]",
    r"V = \frac{{4\pi r^3 }}{3}",
    r"\frac{d}{{dx}}\cos x =  - \sin x",
    r"a\sin \theta  = m\lambda",
    r"r = a\theta",
    r"x( - n) \Leftrightarrow X(e^{ - j\omega } )",
    r"\frac{d}{{dx}}\sin x = \cos x",
    r"\frac{d}{{dx}}arc\csc x = \frac{d}{{dx}}\csc ^{ - 1} x = \frac{{ - 1}}{{\left| x \right|\sqrt {x^2  - 1} }}",
    r"\log K = \frac{{nE^\circ }}{{0.0592}}",
    r"A = \frac{{F_0 }}{{\sqrt {m^2 \left( {\omega _0^2  - \omega ^2 } \right)^2  + b^2 \omega ^2 } }}",
    r"t^n e^{ - at} u(t) \Leftrightarrow \frac{{n!}}{{(s + a)^{n + 1} }}",
    r"\cot \theta  = \frac{1}{{\tan \theta }}",
    r"A = bh",
    r"a\sqrt b  \times c\sqrt d  = ac\sqrt {bd}",
    r"A = bh",
    r"\mathop {\lim }\limits_{x \to 0} \frac{{\sin x}}{x} = 1",
    r"\Delta G^\circ  =  - RT\ln K =  - 2.303RT\log K",
    r"A = \frac{1}{2}(x_1  + x_2 )h",
    r"\delta (n - n_o ) \Leftrightarrow e^{ - j\omega n_o }",
    r"F = ma",
    r"\delta (t) \Leftrightarrow 1",
    r"e^{ - at} \sin (\Omega t)u(t) \Leftrightarrow \frac{\Omega }{{(s + a)^2  + \Omega ^2 }}",
    r"\tan \delta  = \frac{{b\omega }}{{m\left( {\omega _0^2  - \omega ^2 } \right)}}",
    r"S = \frac{{Akc^3 }}{{4\hbar G}}",
    r"\frac{d}{{dx}}\cot x =  - \csc ^2 x",
    r"\frac{d}{{dx}}{\mathop{\rm csch}\nolimits} x =  - \coth x{\mathop{\rm csch}\nolimits} x",
    r"K = ^\circ C + 273",
    r"\frac{{\partial ^2 B}}{{\partial x^2 }} = \frac{1}{{c^2 }}\frac{{\partial ^2 B}}{{\partial t^2 }}",
    r"P = ns",
    r"\tan \theta  = \frac{{\sin \theta }}{{\cos \theta }}",
    r"\cos \left( {\theta _1  \pm \theta _2 } \right) = \cos \theta _1 \cos \theta _2  \mp \sin \theta _1 \sin \theta _2",
    r"\frac{d}{{dx}}b^x  = b^x \ln \left( b \right)",
    r"\frac{d}{{dx}}\int\limits_a^x {f\left( s \right)} ds = f\left( x \right)",
    r"\Delta H^\circ  = \sum {H^\circ _f {\rm{products}}}  - \sum {H^\circ _f {\rm{reactants}}}",
    r"a_1 x_1 (n) + a_2 x_2 (n) \Leftrightarrow a_1 X_1 (z) + a_2 X_2 (z)",
    r"\int {\csc (ax)} dx = \frac{1}{a}\ln \left| {\tan \left( {\frac{{ax}}{2}} \right)} \right| + c",
    r"a^2  - b^2  = \left( {a + b} \right)\left( {a - b} \right)",
    r"\sum\limits_{k = 1}^n {k = \frac{{n\left( {n + 1} \right)}}{2}}",
    r"\sin x = \sum\limits_{n = 1}^\infty  {\frac{{\left( { - 1} \right)^{n - 1} x^{2n - 1} }}{{\left( {2n - 1} \right)!}}}",
    r"y = mx + b",
    r"s_{N - 1}  = \sqrt {\frac{1}{{N - 1}}\sum\limits_{i = 1}^N {\left( {x_i  - \bar x} \right)^2 } }",
    r"V = \frac{{4\pi r^3 }}{3}",
    r"A = \frac{{\theta r^2 }}{2}",
    r"\csc \theta  = \frac{{{\rm{Hypotenuse}}}}{{{\rm{Opposite Side}}}}",
    r"y(x,t) = A_n \cos (\omega _n t + \delta _n )\sin (k_n x)",
    r"x^{ - a}  = \frac{1}{{x^a }}",
    r"y = \log _b \left( x \right){\rm{ iff }}x = b^y",
    r"e^{ - at} \sin (\Omega t)u(t) \Leftrightarrow \frac{\Omega }{{(s + a)^2  + \Omega ^2 }}",
    r"R = \frac{{2GM}}{{c^2 }}",
    r"\tan \theta  = \frac{{\sin \theta }}{{\cos \theta }}",
    r"I = \frac{q}{t}",
    r"\log _b \left( b \right) = 1",
    r"e^{j\omega _o n}  \Leftrightarrow 2\pi \sum\limits_{k =  - \infty }^\infty  {\delta (\omega  - \omega _o  + 2\pi k)}",
    r"\cos \left( { - \theta } \right) = \cos \left( \theta  \right)",
    r"P_{total}  = P_A  + P_B  + P_C  +  \ldots",
    r"E_{Total}  = \frac{1}{2}kA^2",
    r"a + \left( { - a} \right) = 0",
    r"\int\limits_a^b {\frac{d}{{dx}}F\left( x \right)dx}  = F\left( b \right) - F\left( a \right)",
    r"\frac{d}{{dx}}\csc x =  - \csc x\cot x",
    r"S = 4\pi r^2",
    r"x( - n) \Leftrightarrow X(e^{ - j\omega } )",
    r"P_{net}  = e\sigma A\left( {T^4  - T_0^4 } \right)",
    r"x( - n) \Leftrightarrow X^* (e^{j\omega } )",
    r"e^{ \pm i\theta }  = \cos \theta  \pm i\sin \theta",
    r"Ax + By + Cz + D = 0",
    r"\delta (n) \Leftrightarrow 1",
    r"\frac{d}{{dx}}\ln \left( x \right) = \frac{1}{x}",
    r"\frac{d}{{dx}}\arcsin x = \frac{d}{{dx}}sin^{ - 1} x = \frac{1}{{\sqrt {1 - x^2 } }}",
    r"\frac{d}{{dx}}\int\limits_a^x {f\left( s \right)} ds = f\left( x \right)",
    r"\frac{{\left( {x - x_0 } \right)^2 }}{{a^2 }} + \frac{{\left( {y - y_0 } \right)^2 }}{{b^2 }} = 1",
    r"A = \frac{{nsr}}{2} = \frac{{pr}}{2}",
    r"(n + 1)a^n u(n) \Leftrightarrow \frac{1}{{(1 - ae^{ - j\omega } )^2 }},\left| a \right| < 1",
    r"(n + 1)a^n u(n) \Leftrightarrow \frac{1}{{(1 - ae^{ - j\omega } )^2 }},\left| a \right| < 1",
    r"K = ^\circ C + 273",
    r"K_b  = \frac{{\left[ {OH^ -  } \right]\left[ {HB^ +  } \right]}}{{\left[ B \right]}}",
    r"\Gamma \left( x \right) = \int\limits_0^\infty  {s^{x - 1} e^{ - s} ds}",
    r"x^{ - a}  = \frac{1}{{x^a }}",
    r"a\left( {b + c} \right) = ab + ac",
    r"V = \frac{{Bh}}{3} = \frac{{\pi r^2 h}}{3}",
    r"m = NIA\hat n",
    r"{\mathop{\rm var}} \left( {\bar x} \right) = \frac{{\sigma ^2 }}{n}",
    r"\lambda  = \frac{h}{{mv}}",
    r"a = \frac{q}{m}E",
    r"\upsilon  = \sqrt {\frac{B}{\rho }}",
    r"\left( {x - x_0 } \right)^2  + \left( {y - y_0 } \right)^2  + \left( {z - z_0 } \right)^2  = R^2",
    r"F = q{\bf{v}} \times {\bf{B}}",
    r"x = A\cos \left( {\omega t + \delta } \right)",
    r"nx(n) \Leftrightarrow j\frac{{dX(e^{j\omega } )}}{{d\omega }}",
    r"\omega = \omega _0 \sqrt {1 - \left( {\frac{b}{{2m\omega _0 }}} \right)^2 }  = \omega _0 \sqrt {1 - \frac{1}{{4Q^2 }}}",
    r"E_{Total}  = \frac{1}{2}kA^2",
    r"\frac{a}{b} = a \times \left( {\frac{1}{b}} \right)",
    r"V = \frac{{Bh}}{3} = \frac{{\pi r^2 h}}{3}",
    r"A = \pi r_1 r_2",
    r"\cot \theta  = \frac{1}{{\tan \theta }}",
    r"\log _b \left( x \right) = \log _b \left( c \right)\log _c \left( x \right) = \frac{{\log _c \left( x \right)}}{{\log _c \left( b \right)}}",
    r"E = E_0 \exp \left( { - \frac{b}{m}t} \right) = E_0 \exp \left( { - \frac{t}{\tau }} \right)",
    r"\phi  = \frac{{2\pi }}{\lambda }a\sin \theta",
    r"Ku(t) \Leftrightarrow \frac{K}{s}",
    r"a\sqrt b  \times c\sqrt d  = ac\sqrt {bd}",
    r"\frac{d}{{dx}}arc\cot x = \frac{d}{{dx}}\cot ^{ - 1} x = \frac{{ - 1}}{{1 + x^2 }}",
    r"\Delta G^\circ  =  - n\Im E^\circ",
    r"e^{j\omega _o n}  \Leftrightarrow 2\pi \sum\limits_{k =  - \infty }^\infty  {\delta (\omega  - \omega _o  + 2\pi k)}",
    r"Ke^{ - at} u(t) \Leftrightarrow \frac{K}{{s + a}}",
    r"\cot \left( { - \theta } \right) = \cot \left( \theta  \right)",
    r"\sum\limits_{k = 1}^n {k^2  = \frac{{n\left( {n + 1} \right)\left( {2n + 1} \right)}}{6}}",
    r"\upsilon  =  + A\omega \cos \left( {\omega t} \right) =  - A\omega \sin \left( {\omega t - \frac{\pi }{2}} \right)",
    r"\varepsilon  = \frac{{\sqrt {a^2  - b^2 } }}{a}",
    r"\sum\limits_{k = 1}^n {ar^{k - 1}  = \frac{{a\left( {1 - r^n } \right)}}{{1 - r}}}",
    r"x^{ - a}  = \frac{1}{{x^a }}",
    r"D = \frac{m}{V}",
    r"\left( {a + b} \right)\left( {c + d} \right) = ac + ad + bc + bd",
    r"pH =  - \log \left[ {H^ +  } \right]",
    r"x^{ - a}  = \frac{1}{{x^a }}",
    r"\frac{d}{{dx}}\sin x = \cos x",
    r"n^2 u(n) \Leftrightarrow \frac{{z\left( {z + 1} \right)}}{{\left( {z - 1} \right)^3 }},\left| z \right| > 1",
    r"a \times 0 = 0",
    r"C = \frac{Q}{V} = \frac{{\varepsilon _0 A}}{s}",
    r"\frac{d}{{dx}}\int\limits_a^x {f\left( s \right)} ds = f\left( x \right)",
    r"x(0^ +  ) = \mathop {\lim }\limits_{s \to \infty } sX(s)",
    r"\tan \theta  = \frac{{\sec \theta }}{{\csc \theta }}",
    r"F = \eta \frac{{\upsilon A}}{z}",
    r"y = \frac{1}{{\sqrt {2\pi } }}e^{ - \frac{{z^2 }}{2}}  = .3989e^{ - 5z^2 }",
    r"a = \frac{q}{m}E",
    r"\Delta S^\circ  = \sum {S^\circ {\rm{products}}}  - \sum {S^\circ {\rm{reactants}}}",
    r"x(n)y(n) \Leftrightarrow \frac{1}{{2\pi }}\int\limits_{ - \pi }^\pi  {X(e^{j\theta } )Y(e^{j(\omega  - \theta )} )d\theta }",
    r"\int {\csc (ax)} dx = \frac{1}{a}\ln \left| {\tan \left( {\frac{{ax}}{2}} \right)} \right| + c",
    r"S = 4\pi r^2",
    r"\cos \left( {\theta _1  \pm \theta _2 } \right) = \cos \theta _1 \cos \theta _2  \mp \sin \theta _1 \sin \theta _2",
    r"d = \sqrt {\left( {x_1  - x_2 } \right)^2  + \left( {y_1  - y_2 } \right)^2 }",
    r"a\left( {b + c} \right) = ab + ac",
    r"\left( {a \times b} \right) \times c = a \times \left( {b \times c} \right) = a \times b \times c",
    r"\cos \left( { - \theta } \right) = \cos \left( \theta  \right)",
    r"h(n)x(n) \Leftrightarrow \frac{1}{{2\pi j}}\oint_C {H\left( v \right)X\left( {z/v} \right)\mathop v\nolimits^{ - 1} dv}",
    r"x( - n) \Leftrightarrow X(e^{ - j\omega } )",
    r"a^3  - b^3  = \left( {a - b} \right)\left( {a^2  + ab + b^2 } \right)",
    r"\frac{d}{{dx}}\cos x =  - \sin x",
    r"\left( {a + b} \right)^2  = a^2  + 2ab + b^2",
    r"P = ns",
    r"x^2  + x\left( {a + b} \right) + ab = \left( {x + a} \right)\left( {x + b} \right)",
    r"\Delta G^\circ  = \Delta H^\circ  - T\Delta S^\circ",
    r"x( - n) \Leftrightarrow X^* (e^{j\omega } )",
    r"R = \frac{{2GM}}{{c^2 }}",
    r"P = ns",
    r"\oint_C {E \cdot d\ell  =  - \frac{d}{{dt}}} \int_S {B_n dA}",
    r"\frac{{\left( {x - x_0 } \right)^2 }}{{a^2 }} + \frac{{\left( {y - y_0 } \right)^2 }}{{b^2 }} = \frac{{\left( {z - z_0 } \right)^2 }}{{c^2 }}",
    r"R = \frac{{\Delta x}}{{kA}}",
    r"\frac{d}{{dx}}\arcsin x = \frac{d}{{dx}}sin^{ - 1} x = \frac{1}{{\sqrt {1 - x^2 } }}",
    r"V = Bh = \pi r^2 h",
    r"\cot \theta  = \frac{{\cos \theta }}{{\sin \theta }}",
    r"\Gamma \left( x \right) = \int\limits_0^\infty  {s^{x - 1} e^{ - s} ds}",
    r"\frac{d}{{dx}}\cosh x = \sinh x",
    r"A = \frac{{F_0 }}{{\sqrt {m^2 \left( {\omega _0^2  - \omega ^2 } \right)^2  + b^2 \omega ^2 } }}",
    r"a\sqrt b  \pm c\sqrt b  = \left( {a \pm c} \right)\sqrt b",
    r"\pi  = \frac{{nRT}}{V}i",
    r"K = ^\circ C + 273",
    r"\Gamma \left( a \right) = \int\limits_0^\infty  {s^{a - 1} } e^{ - s} ds",
    r"\Delta S^\circ  = \sum {S^\circ {\rm{products}}}  - \sum {S^\circ {\rm{reactants}}}",
    r"\mathop {\lim }\limits_{x \to \infty } \frac{1}{{x^n }} = 0",
    r"a_{av}  = \frac{{\Delta \upsilon }}{{\Delta t}}",
    r"L = \frac{{\phi _m }}{I} = \mu _0 n^2 A\ell",
    r"\frac{d}{{dx}}\ln \left( x \right) = \frac{1}{x}",
    r"T = \frac{{\hbar c^3 }}{{8\pi kGM}}",
    r"e^{ - at} \sin (\Omega t)u(t) \Leftrightarrow \frac{\Omega }{{(s + a)^2  + \Omega ^2 }}",
    r"\cot \left( { - \theta } \right) = \cot \left( \theta  \right)",
    r"x^{\left( {\frac{1}{2}} \right)}  = \sqrt x",
    r"\Delta H^\circ  = \sum {H^\circ _f {\rm{products}}}  - \sum {H^\circ _f {\rm{reactants}}}",
    r"\mathop {\lim }\limits_{x \to 0} \frac{{\sin x}}{x} = 1",
    r"u(n) \Leftrightarrow \frac{z}{{z - 1}},\left| z \right| > 1",
    r"\cot \left( { - \theta } \right) = \cot \left( \theta  \right)",
    r"n^2 a^n u(n) \Leftrightarrow \frac{{az(z + a)}}{{\left( {z - a} \right)^3 }},\left| z \right| > \left| a \right|",
    r"I = \frac{q}{t}",
    r"\frac{{\left( {x - x_0 } \right)^2 }}{{a^2 }} + \frac{{\left( {y - y_0 } \right)^2 }}{{b^2 }} = 1",
    r"\cot \theta  = \frac{{\cos \theta }}{{\sin \theta }}",
    r"\upsilon  =  + A\omega \cos \left( {\omega t} \right) =  - A\omega \sin \left( {\omega t - \frac{\pi }{2}} \right)",
    r"\frac{{\left( {x - x_0 } \right)^2 }}{{a^2 }} + \frac{{\left( {y - y_0 } \right)^2 }}{{b^2 }} = \frac{{\left( {z - z_0 } \right)^2 }}{{c^2 }}",
    r"\oint_S {E_n dA = \frac{1}{{\varepsilon _0 }}} Q_{inside}",
    r"h(n)x(n) \Leftrightarrow \frac{1}{{2\pi j}}\oint_C {H\left( v \right)X\left( {z/v} \right)\mathop v\nolimits^{ - 1} dv}",
    r"\oint_C {E \cdot d\ell  =  - \frac{d}{{dt}}} \int_S {B_n dA}",
    r"X(s) = \int\limits_0^\infty  {x(t)e^{ - st} dt}",
    r"\log _b \left( {xy} \right) = \log _b \left( x \right) + \log _b \left( y \right)",
    r"\xi  = \oint_C {E \cdot d\ell }",
    r"\Delta V = V_b  - V_a  = \frac{{\Delta U}}{{q_0 }} =  - \int_a^b {E \cdot d\ell }",
    r"\phi  = \int_S {{\bf{E}} \cdot {\bf{\hat n}}dA}",
    r"\left( {a + b} \right)\left( {c + d} \right) = ac + ad + bc + bd",
    r"\sin x = \sum\limits_{n = 1}^\infty  {\frac{{\left( { - 1} \right)^{n - 1} x^{2n - 1} }}{{\left( {2n - 1} \right)!}}}",
    r"d = \sqrt {\left( {x_1  - x_2 } \right)^2  + \left( {y_1  - y_2 } \right)^2  + \left( {z_1  - z_2 } \right)^2 }",
    r"\oint_S {E_n dA = \frac{1}{{\varepsilon _0 }}} Q_{inside}",
    r"\int {\sec (ax)} dx = \frac{1}{a}\ln \left| {\tan \left( {\frac{{ax}}{2} + \frac{\pi }{4}} \right)} \right| + c",
    r"x(0^ +  ) = \mathop {\lim }\limits_{s \to \infty } sX(s)",
    r"\log K = \frac{{nE^\circ }}{{0.0592}}",
    r"\Delta x = x - x_0  = \upsilon _0 t + \frac{1}{2}at^2",
    r"A = \frac{{F_0 }}{{\sqrt {m^2 \left( {\omega _0^2  - \omega ^2 } \right)^2  + b^2 \omega ^2 } }}",
    r"e^{j\omega _o n}  \Leftrightarrow 2\pi \sum\limits_{k =  - \infty }^\infty  {\delta (\omega  - \omega _o  + 2\pi k)}",
    r"x(n - m) \Leftrightarrow z^{ - m} X(z)",
    r"\left( {a + b} \right)^2  = a^2  + 2ab + b^2",
    r"M_b  = np",
    r"y = \log _b \left( x \right){\rm{ iff }}x = b^y",
    r"n^3 a^n u(n) \Leftrightarrow \frac{{az(z^2  + 4az + a^2 )}}{{\left( {z - a} \right)^4 }},\left| z \right| > \left| a \right|",
    r"\log K = \frac{{nE^\circ }}{{0.0592}}",
    r"V = \frac{{V_\theta  e^{ - kr} }}{r}",
    r"A = \frac{{F_0 }}{{\sqrt {m^2 \left( {\omega _0^2  - \omega ^2 } \right)^2  + b^2 \omega ^2 } }}",
    r"\frac{d}{{dx}}\arctan x = \frac{d}{{dx}}\tan ^{ - 1} x = \frac{1}{{1 + x^2 }}",
    r"e^{ \pm i\theta }  = \cos \theta  \pm i\sin \theta",
    r"\tan \left( { - \theta } \right) =  - \tan \left( \theta  \right)",
    r"P = 2\pi r",
    r"Ke^{ - at} u(t) \Leftrightarrow \frac{K}{{s + a}}",
    r"\frac{d}{{dx}}\sinh x = \cosh x",
    r"\frac{d}{{dx}}\cos x =  - \sin x",
    r"\oint_S {E_n dA = \frac{1}{{\varepsilon _0 }}} Q_{inside}",
    r"\sigma  = \sqrt {\mu _2 }",
    r"\int {\tan (ax)} dx =  - \frac{1}{a}\ln \left| {\cos (ax)} \right| + c",
    r"C = \frac{Q}{V} = \frac{{\varepsilon _0 A}}{s}",
    r"ax(n) + by(n) \Leftrightarrow aX(e^{j\omega } ) + bY(e^{j\omega } )",
    r"\frac{{d^n x(t)}}{{dt^n }} \Leftrightarrow s^n X(s)",
    r"y = \log _b \left( x \right){\rm{ iff }}x = b^y",
    r"\frac{{P_1 V_1 }}{{n_1 T_1 }} = \frac{{P_2 V_2 }}{{n_2 T_2 }}",
    r"tu(t) \Leftrightarrow \frac{1}{{s^2 }}",
    r"\log _b \left( x \right) = \log _b \left( c \right)\log _c \left( x \right) = \frac{{\log _c \left( x \right)}}{{\log _c \left( b \right)}}",
    r"K = \frac{1}{2}kA^2 \sin ^2 \left( {\omega t + \delta } \right)",
    r"F = ma",
    r"\log _b \left( x \right) = \log _b \left( c \right)\log _c \left( x \right) = \frac{{\log _c \left( x \right)}}{{\log _c \left( b \right)}}",
    r"Ku(t) \Leftrightarrow \frac{K}{s}",
    r"{\rm{Stress}} = \frac{F}{A}",
    r"F_2  = \frac{{F_1 }}{{A_1 }}A_2  = \frac{{A_2 }}{{A_1 }}F_1",
    r"m = NIA\hat n",
    r"1 + \tan ^2 \theta  = \sec ^2 \theta",
    r"\Delta G^\circ  = \sum {G^\circ _f {\rm{products}}}  - \sum {G^\circ _f {\rm{reactants}}}",
    r"\int {x^n } dx = \frac{{x^{n + 1} }}{{n + 1}},(n \ne  - 1)",
    r"P = 4s",
    r"a^3  - b^3  = \left( {a - b} \right)\left( {a^2  + ab + b^2 } \right)",
    r"A = \frac{{\theta r^2 }}{2}",
    r"\frac{d}{{dx}}\arctan x = \frac{d}{{dx}}\tan ^{ - 1} x = \frac{1}{{1 + x^2 }}",
    r"\sigma ^2  = \mu _2  = \sum {\left( {x - \mu _1 } \right)^2 P\left( x \right)}",
    r"x(n)y(n) \Leftrightarrow \frac{1}{{2\pi }}\int\limits_{ - \pi }^\pi  {X(e^{j\theta } )Y(e^{j(\omega  - \theta )} )d\theta }",
    r"\left( {x - x_0 } \right)^2  + \left( {y - y_0 } \right)^2  + \left( {z - z_0 } \right)^2  = R^2",
    r"\log _b \left( {xy} \right) = \log _b \left( x \right) + \log _b \left( y \right)",
    r"S = 2lw + 2lh + 2wh",
    r"\upsilon  = \sqrt {\frac{B}{\rho }}",
    r"\cot \theta  = \frac{{\csc \theta }}{{\sec \theta }}",
    r"x^{ - a}  = \frac{1}{{x^a }}",
    r"\delta (n - n_o ) \Leftrightarrow e^{ - j\omega n_o }",
    r"\sum\limits_{k = 1}^n {ar^{k - 1}  = \frac{{a\left( {1 - r^n } \right)}}{{1 - r}}}",
    r"\delta (n) \Leftrightarrow 1",
    r"F = \eta \frac{{\upsilon A}}{z}",
    r"\frac{d}{{dx}}\sin x = \cos x",
    r"r = a\theta",
    r"\frac{d}{{dx}}\sin x = \cos x",
    r"S = 6x^2",
    r"t^n u(t) \Leftrightarrow \frac{{n!}}{{s^{n + 1} }}",
    r"n^2 u(n) \Leftrightarrow \frac{{z\left( {z + 1} \right)}}{{\left( {z - 1} \right)^3 }},\left| z \right| > 1",
    r"V = \frac{{V_\theta  e^{ - kr} }}{r}",
    r"E = mc^2",
    r"tx(t)u(t) \Leftrightarrow \frac{{ - dX(s)}}{{ds}}",
    r"a\sqrt b  \times c\sqrt d  = ac\sqrt {bd}",
    r"\upsilon ^2  = \upsilon _0 ^2  + 2a\Delta x",
    r"\sin x = \sum\limits_{n = 1}^\infty  {\frac{{\left( { - 1} \right)^{n - 1} x^{2n - 1} }}{{\left( {2n - 1} \right)!}}}",
    r"\cot ^2 \theta  + 1 = \csc ^2 \theta",
    r"S = 2\pi r^2  + 2\pi rh",
    r"\frac{d}{{dx}}\int\limits_a^x {f\left( s \right)} ds = f\left( x \right)",
    r"y = \frac{1}{{\sqrt {2\pi } }}e^{ - \frac{{z^2 }}{2}}  = .3989e^{ - 5z^2 }",
    r"E_k  = \frac{1}{2}mv^2",
    r"V = \frac{{V_\theta  e^{ - kr} }}{r}",
    r"\frac{{\left( {x - x_0 } \right)^2 }}{{a^2 }} + \frac{{\left( {y - y_0 } \right)^2 }}{{b^2 }} + \frac{{\left( {z - z_0 } \right)^2 }}{{c^2 }} = 1",
    r"\log _b \left( 1 \right) = 0",
    r"\sin x = \sum\limits_{n = 1}^\infty  {\frac{{\left( { - 1} \right)^{n - 1} x^{2n - 1} }}{{\left( {2n - 1} \right)!}}}",
    r"\frac{d}{{dx}}\arcsin x = \frac{d}{{dx}}sin^{ - 1} x = \frac{1}{{\sqrt {1 - x^2 } }}",
    r"e^{j\omega _o n}  \Leftrightarrow 2\pi \sum\limits_{k =  - \infty }^\infty  {\delta (\omega  - \omega _o  + 2\pi k)}",
    r"\sum\limits_{k = 1}^n {ar^{k - 1}  = \frac{{a\left( {1 - r^n } \right)}}{{1 - r}}}",
    r"x(0^ +  ) = \mathop {\lim }\limits_{s \to \infty } sX(s)",
    r"A = \frac{{x_1 x_2 }}{2}",
    r"\sum\limits_{k = 1}^n {k = \frac{{n\left( {n + 1} \right)}}{2}}",
    r"\Delta G^\circ  =  - RT\ln K =  - 2.303RT\log K",
    r"x^a y^a  = \left( {xy} \right)^a",
    r"pH =  - \log \left[ {H^ +  } \right]",
    r"\frac{d}{{dx}}arc\csc x = \frac{d}{{dx}}\csc ^{ - 1} x = \frac{{ - 1}}{{\left| x \right|\sqrt {x^2  - 1} }}",
    r"PV = k",
    r"X(e^{j\omega } ) = x(n)e^{ - j\omega n} ,\omega  {\rm{in radians}}",
    r"\sin \left( { - \theta } \right) =  - \sin \left( \theta  \right)",
    r"\log _b \left( b \right) = 1",
    r"n = \frac{{\sin {\rm{ }}i}}{{\sin {\rm{ }}r}} = \frac{{{\rm{depth}}}}{{{\rm{apparent depth}}}}",
    r"P = a + b + c",
    r"n^3 a^n u(n) \Leftrightarrow \frac{{az(z^2  + 4az + a^2 )}}{{\left( {z - a} \right)^4 }},\left| z \right| > \left| a \right|",
    r"\cos \left( { - \theta } \right) = \cos \left( \theta  \right)",
    r"\csc \theta  = \frac{{{\rm{Hypotenuse}}}}{{{\rm{Opposite Side}}}}",
    r"\left( {a + b} \right)\left( {c + d} \right) = ac + ad + bc + bd",
    r"{\rm{a + 0 = a}}",
    r"\frac{d}{{dx}}\cosh x = \sinh x",
    r"E_k  = \frac{1}{2}mv^2",
    r"X(z) \buildrel \Delta \over = \sum\limits_{n =  - \infty }^\infty  {x(n)z^{ - n} }",
    r"\frac{a}{b} = a \times \left( {\frac{1}{b}} \right)",
    r"A = \frac{{\theta r^2 }}{2}",
    r"\Delta S^\circ  = \sum {S^\circ {\rm{products}}}  - \sum {S^\circ {\rm{reactants}}}",
    r"\cot \theta  = \frac{{\csc \theta }}{{\sec \theta }}",
    r"\frac{{KE}}{{mole}} = \frac{3}{2}RTn",
    r"\sin (\Omega t)u(t) \Leftrightarrow \frac{\Omega }{{(s^2  + \Omega ^2 )}}",
    r"n = \frac{I}{{Aq\upsilon _d }} = \frac{I}{{wte\upsilon _d }}",
    r"\frac{d}{{dx}}\cos x =  - \sin x",
    r"x(n)y(n) \Leftrightarrow \frac{1}{{2\pi }}\int\limits_{ - \pi }^\pi  {X(e^{j\theta } )Y(e^{j(\omega  - \theta )} )d\theta }",
    r"a^n u(n) \Leftrightarrow \frac{z}{{\left( {z - a} \right)}},\left| z \right| > \left| a \right|",
    r"\phi _{net}  = \int_S {E_n dA = } \frac{1}{{\varepsilon _0 }}Q_{inside}  = 4\pi kQ_{inside}",
    r"\sum\limits_{k = 1}^n {ar^{k - 1}  = \frac{{a\left( {1 - r^n } \right)}}{{1 - r}}}",
    r"P_{net}  = e\sigma A\left( {T^4  - T_0^4 } \right)",
    r"\mathop {\lim }\limits_{x \to  - \infty } \tan ^{ - 1} \left( x \right) =  - \frac{\pi }{2}",
    r"{\rm{Stress}} = \frac{F}{A}",
    r"P = ns",
    r"\log _b \left( 1 \right) = 0",
    r"e^{ \pm i\theta }  = \cos \theta  \pm i\sin \theta",
    r"n = \frac{{\sin {\rm{ }}i}}{{\sin {\rm{ }}r}} = \frac{{{\rm{depth}}}}{{{\rm{apparent depth}}}}",
    r"\sin (\omega _o n + \theta )u(n) \Leftrightarrow \frac{{z[z\sin \theta  + \sin (\omega _o  - \theta )]}}{{\left( {z^2  - 2z\cos \omega _o  + 1} \right)}},\left| z \right| > 1",
    r"\frac{d}{{dx}}\cot x =  - \csc ^2 x",
    r"\cot ^2 \theta  + 1 = \csc ^2 \theta",
    r"I = \frac{{\Delta Q}}{{\Delta t}} = kA\frac{{\Delta T}}{{\Delta x}}",
    r"\frac{{\left( {x - x_0 } \right)^2 }}{{a^2 }} + \frac{{\left( {y - y_0 } \right)^2 }}{{b^2 }} = \frac{{\left( {z - z_0 } \right)^2 }}{{c^2 }}",
    r"a\sqrt b  \pm c\sqrt b  = \left( {a \pm c} \right)\sqrt b",
    r"n^2 u(n) \Leftrightarrow \frac{{z\left( {z + 1} \right)}}{{\left( {z - 1} \right)^3 }},\left| z \right| > 1",
    r"\frac{d}{{dx}}e^{ax}  = ae^{ax}",
    r"nx\left( n \right) \Leftrightarrow  - z\frac{{dX(z)}}{{dz}}",
    r"S = 4\pi r^2",
    r"\delta (t) \Leftrightarrow 1",
    r"\log K = \frac{{nE^\circ }}{{0.0592}}",
    r"\mu _n \left( a \right) = \sum {\left( {x - a} \right)^n P\left( x \right)}",
    r"x( - n) \Leftrightarrow X(e^{ - j\omega } )",
    r"V = lhw",
    r"\mu _n \left( a \right) = \sum {\left( {x - a} \right)^n P\left( x \right)}",
    r"S = \frac{{E \times B}}{{\mu _0 }}",
    r"\left( {a + b} \right)\left( {c + d} \right) = ac + ad + bc + bd",
    r"\frac{d}{{dx}}\coth x = 1 - \coth ^2 x",
    r"\phi _m  = \int_S {N{\bf{B}} \cdot {\bf{\hat n}}dA = } \int_S {NB_n dA}",
    r"y = \log _b \left( x \right){\rm{ iff }}x = b^y",
    r"n = \frac{{\sin {\rm{ }}i}}{{\sin {\rm{ }}r}} = \frac{{{\rm{depth}}}}{{{\rm{apparent depth}}}}",
    r"h(n) * x(n) \Leftrightarrow H(z)X(z)",
    r"- \frac{{\hbar ^2 }}{{2m}}\frac{{\partial ^2 \psi (x,t)}}{{\partial x^2 }} + U(x)\psi (x,t) = i\hbar \frac{{\partial \psi (x,t)}}{{\partial t}}",
    r"\tan \delta  = \frac{{b\omega }}{{m\left( {\omega _0^2  - \omega ^2 } \right)}}",
    r"\sin \left( { - \theta } \right) =  - \sin \left( \theta  \right)",
    r"\int {x^n } dx = \frac{{x^{n + 1} }}{{n + 1}},(n \ne  - 1)",
    r"s_N  = \sqrt {\frac{1}{N}\sum\limits_{i = 1}^N {\left( {x_i  - \bar x} \right)^2 } }",
    r"\sin (\Omega t)u(t) \Leftrightarrow \frac{\Omega }{{(s^2  + \Omega ^2 )}}",
    r"\oint_S {E_n dA = \frac{1}{{\varepsilon _0 }}} Q_{inside}",
    r"\phi _{net}  = \int_S {E_n dA = } \frac{1}{{\varepsilon _0 }}Q_{inside}  = 4\pi kQ_{inside}",
    r"A = \frac{{F_0 }}{{\sqrt {m^2 \left( {\omega _0^2  - \omega ^2 } \right)^2  + b^2 \omega ^2 } }}",
    r"B = \mu _0 nI",
    r"R = \frac{{m_e k^2 e^4 }}{{4\pi c\hbar ^3 }}",
    r"a = \frac{q}{m}E",
]
